import { Inter as FontSans } from "next/font/google"
import "./globals.css" 
import { Toaster } from 'react-hot-toast';


import { cn } from "@/lib/utils"
import { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import NavBar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";


export const metadata: Metadata = { title: "AniMatch", description: "Generated by create next app", };

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      > 
        <NavBar/>
        <Toaster position="bottom-right" reverseOrder={false} />
        {children}
      </body>

    </html>
    </ClerkProvider>
  )
}
